### PR TITLE
Add hardware support

### PR DESCRIPTION
**Pull request by svenwml**
As requested in #600 and #278 , support for external hardware would be great. @skief and me did an implementation for that.

Supported hardware:

- MIDI controllers (Sliders / Rotary Potentiometers with linear mapping, Buttons, Rotary Encoders)
- deej controllers (using the serial port, suitable e.g. for Arduino projects) (Sliders / Rotary Potentiometers, but makers can also map buttons or rotary encoders to linear values in their microcontroller-code to use all functionalities)

-> Extensive configuration possibilities including offset and scaling options.

Supported commands:

- Changing device and application volumes.
- Muting devices and applications.
- Change the default output device.

Best regards,
@skief and Sven

eartrumpet_midi_animation

eartrumpet_midi_settings_1

eartrumpet_midi_settings_2

### CODE REVIEW

**Comment by WolfganP** [comment]
Excellent addition! I use https://xmmc.de/touchdaw/ as a virtual MIDI controller for other audio software, definitely will test this feature once merged.

**Comment by svenwml** [comment]
> 
> 
> Excellent addition! I use https://xmmc.de/touchdaw/ as a virtual MIDI controller for other audio software, definitely will test this feature once merged.

Thanks for that tip! Did not know this software, will try it!

**Comment by davuxcom** [comment]
Thanks @svenwml and @skief - you guys clearly put a lot of work into this!

We think this is a great candidate for our new third-party addon system, which has been in EarTrumpet for a while but will soon become public.

I've taken the liberty of converting your PR into a standalone DLL that EarTrumpet will load. It will do all the same things but doesn't require any changes to EarTrumpet.

Download it here:
[EarTrumpet.HardwareSupportAddon.zip](https://github.com/File-New-Project/EarTrumpet/files/5900804/EarTrumpet.HardwareSupportAddon.zip)

There is a git repository. I layered all the changes and it should be pretty clear to see what I did. I imported almost all the files without any changes, but had to fix namespaces and then resources and some really small stuff.

To use it, you need to set up your folder structure so the folders are peers of each other:
```
EarTrumpet/EarTrumpet.vs15.sln
EarTrumpet.HardwareSupportAddon/EarTrumpet-WithAddons.sln
```

Try to avoid making changes in these folders as we're likely to change/remove these in the near future:
```
AddonPackage
EarTrumpet.Shared
```

We'll reach out soon with documentation and more information about how to deploy and distribute addons, but I think this is enough to get you started. Let me know if you have questions.

**Comment by svenwml** [comment]
@davuxcom, this looks perfect! Thanks for your work porting our addition to a separate addon. It works out of the box. Is it okay for you if we take the contents of the archive you uploaded to a new repository so that we can continue work on the addon from there?

Concerning the combobox hack:

The problem occurs when an item of our comboboxes is changed. As soon as a new selection from the box is clicked, the program throws an exception:

grafik

It seems that the problem is that we hold our items as strings, casting to EarTrumpet.UI.ViewModels.SettingsSearchItemViewModel fails. Is there a way for us to override the OnComboBoxItemPreviewMouseLeftButtonDown method locally for our plugin to solve this problem without having to do changes in the EarTrumpet code?

We are looking forward to further documentation for deployment and distributon of the addon, this is going to be good!

**Comment by davuxcom** [comment]
> Is it okay for you if we take the contents of the archive you uploaded to a new repository so that we can continue work on the addon from there?

Yes absolutely, please do.

> The problem occurs when an item of our comboboxes is changed. As soon as a new selection from the box is clicked, the program throws an exception:

Ahh my apologies, I looked at this and was wondering how it was even in play. I see the bug now, and can repro it by trying to add new hardware and select a device from the list.

The bug is that `App.xaml` has a default style for `ComboBoxItem`:
```
<Style TargetType="{x:Type ComboBoxItem}">
...
    <Setter Property="b:ComboBoxEx.ItemClickEnabled" Value="True" />
...
</Style>
```
And this is necessary for Settings page Search items but nothing else. We didn't notice because `ComboBox` isn't a popular control in the other addons written so far. There's a fix in EarTrumpet but you can work around it by making sure that when a `ComboBoxItem` is created in one of your windows, it doesn't have the property set to `True`.

So for each of your 3 windows using `ComboBox`, add a reference:
```
xmlns:b="clr-namespace:EarTrumpet.UI.Behaviors;assembly=EarTrumpet"
```
Then add a style:
```
<Window.Resources>
    <Style TargetType="{x:Type ComboBoxItem}" BasedOn="{StaticResource {x:Type ComboBoxItem}}">
        <Setter Property="b:ComboBoxEx.ItemClickEnabled" Value="False" />
    </Style>
</Window.Resources>
```

This fixes it but doesn't give you the 'item hover over' visuals that you should really have. Depending on whether you want the Win10 look or the Win7 look, the styles will have to be changed.

IMPORTANT: `AddonResources.xaml` will be merged directly into App.xaml. So please avoid taking the above style and adding it directly into your `AddonResources.xaml` without an `x:Key` - this will look like it works great but will break EarTrumpet settings.

**Comment by svenwml** [comment]
Thank you very much for the detailed explanaition! Everything is fixed and running.

For everyone who's interested: We manage the addon in the following repository from now on:
https://github.com/applapp/EarTrumpet.HardwareSupportAddon

As soon as we receive further information on deployment and distribution, we plan to release the plugin so that users do not have to build it themselves.

**Pull request closed without merging**
