### PR TITLE
Added the 21H1 update to the readme

### PR DESCRIPTION
**Pull request by thepwrtank18**

### CODE REVIEW

**Comment by riverar** [comment]
We don't support Windows 11 Insider Preview yet, can you remove those edits?

**Comment by riverar** [comment]
Thanks! Working on Windows 11 support now.

**Comment by riverar** [comment]
This PR was targeting the wrong branch (should be `dev`). I made the change but you'll need to rebase your changes and push (or submit a new PR). Appreciate it!

**Comment by thepwrtank18** [comment]
Seems to have done it automatically from my end on GitHub.

**Pull request merged**
