### PR TITLE
Update Japanese translation

### PR DESCRIPTION
**Pull request by maboroshin**
Hi! I updated.

* Update to the latest string. (Maybe. Japanese and English don't match)
* Improve machine translation like.
* Match the words to the Windows Japanese edition. (e.g. "音量ミキサー", not "ボリュームミキサー")

### CODE REVIEW

**Comment by riverar** [comment]
Thanks @maboroshin, can you verify your changes are https://crowdin.com/translate/eartrumpet/32/en-ja? I sync up resources from CrowdIn.

**Comment by maboroshin** [comment]
@riverar : Hi!

* Publicize Crowdin's existence, e.g. on Raedme. It will be easy to participate.
* Crowdin has a recent translations. So, Currently, I can only suggest translations. I don't seem to have authority the overwrite.

**Comment by riverar** [comment]
Thanks, closing this PR. Looks like Japanese is ready to go on Crowdin, thanks!

**Comment by maboroshin** [comment]
@riverar:
The translation remains the same as before.

I have added the translation candidates on Crowdin. It appears that you have the authority to make translation decisions.
I can only enter suggestions, not change the translations.

**Comment by riverar** [comment]
@maboroshin Thanks, I approved them all just now. Will get them checked into the dev branch shortly.

**Pull request closed without merging**
