### PR TITLE
Fix for Windows 10 audio device switching

### PR DESCRIPTION
**Pull request by sozercan**

### CODE REVIEW

**Comment by riverar** [comment]
Does audio device switching not work for you? Can you provide more information here?

**Comment by sozercan** [comment]
I believe the GUID of the internal interface was changed pre-TH1. Switching didn't work for me before. After the change, it works.

AudioSwitcher had the same issue: https://github.com/davkean/audio-switcher/commit/55f41d38ce30becb66e82f4cddd29120eb2831ad

**Comment by ioannis-e** [comment]
Great! this works for me on: Microsoft Windows [Version 10.0.10586]

**Comment by riverar** [comment]
@sozercan Are you on TH2 as well? Trying to track down the root cause here as the GUID is correct.

**Comment by sozercan** [comment]
@riverar yup, works on TH2. Just tested it on RS1, crashes there.

**Comment by riverar** [comment]
Looks like Microsoft broke app compat with QueryAudioSessionManager2-related work in TH2 AudioSes.dll and filled the pot hole some time between post-TH2 and RS1. Investigating a fix.

**Pull request closed without merging**
