### PR TITLE
Drag&Drop to change app device (discussion #662)

### PR DESCRIPTION
**Pull request by Masurov**
As discussed in https://github.com/File-New-Project/EarTrumpet/discussions/662, here is the drag&drop feature.

I used gong wpf dragdrop package to make it easier. Feel free to tell me if the project guidelines are not followed.

### CODE REVIEW

**Comment by riverar** [comment]
Will review this, but one question that immediately comes to mind: How does a user return an app to the state in which it follows the "default" device? I feel like this may greatly confuse users as apps will start becoming attached to specific devices.

**Comment by Masurov** [comment]
Good point ! I naively duplicated the "transfer application" button command to drag and drop action. You're right, this will encourage users to force application output on a device.

To be self explanatory, EarTrumpet could show that the current application-device assigment is forced or not. What about adding a "pinned" clickable icon on a application if it is assigned on this specific device ? Clicking on the pin button would reassign the application on default device and remove the pin icon.

Would be interested in your thought.

**Comment by Masurov** [comment]
Something like this but I don't know exactly where to put the pin

image

**Comment by ryantheleach** [comment]
After starting a drag event, you could spawn a drop target that says default on it, that is hidden otherwise.

**Comment by sphinx9** [comment]
Is this ever going to be implemented?

**Comment by yani** [comment]
> Will review this, but one question that immediately comes to mind: How does a user return an app to the state in which it follows the "default" device? I feel like this may greatly confuse users as apps will start becoming attached to specific devices.

Maybe something like this.
image

And instead of an icon it might be interested to do it like this:
image
Could either mean default device or the other way around.

**Comment by bigplayer-ai** [comment]
Why this still not updated? How can I get this version of eartrumpet?

**Comment by bigplayer-ai** [comment]
I compiled this but I wish if you can add hovering over the app icon to know the source of it. 
For example multiple chrome windows opened will show only chrome icons it is hard to know which chrome window you want to switch it's audio.

**Comment by bigplayer-ai** [comment]
> 



> @bigplayer-ai There are still outstanding design questions / issues to resolve and it hasn't been high priority to resolve because this core functionality already exists (right-click an app).

this is taking forever :(
Can you help me get .msi to install this? my compilation/build failed :(

**Comment by riverar** [comment]
This feature still needs design work and will start falling behind with some major merges coming up. Closing for now.

**Pull request closed without merging**
