### PR TITLE
Updated Chocolatey icon and Startup method

### PR DESCRIPTION
**Pull request by xmha97**
Changes:
- Updated Chocolatey icon
- Updated startup method

### CODE REVIEW

**Comment by xmha97** [comment]
@riverar Please approve this pull request.

**Comment by riverar** [comment]
I'll have to test the startup changes, standby.

**Comment by xmha97** [comment]
I'm waiting for you to do this test. ⌛

In the chocolatey installation script, I used the registry for the startup because the app runs faster.

Also, before, the app was added in the startup of all users, but now the app is added only in the current startup user.

**Comment by xmha97** [comment]
@riverar I'm waiting for you to do this test. ⌛

In the chocolatey installation script, I used the registry for the startup (instead of creating shortcut in startup folder) because the app runs faster.

Also, before, the app was added in the startup of all users, but now the app is added only in the current startup user.

**Comment by riverar** [comment]
Ah man, this was supposed to target dev. I'll need to undo that now.

**Comment by riverar** [comment]
@xmha97 Can you send a new PR and target `dev`? I'll merge it in when I see it.

**Pull request merged**
